language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
notifications:
  # post build updates to Slack
  slack: cs221rmj:heO2XVXFlrpYiy9RTLPItJiH
script:
  - cwd=$(pwd)
  - cd ${cwd}/src/
  # run make
  - make
  # run Model Test
  - python ModelTest.py
  # run Player Test
  - python PlayerTest.py
